### ISSUE TITLE
Would be good to show also total volume difference between seasonal influenza and COVID-19

### ISSUE THREAD

**Issue by schrepfler** [mbevand/covid19-age-stratified-ifr#1]

**Comment by mbevand** [comment]
Total volume?

**Comment by MikeJayDee** [comment]
I assume @schrepfler means IFR multiplied by attack rate to show the difference in the proportion of the population potentially at risk (probably 50-80% for COVID-19, and maybe 10% for a typical seasonal flu). Not sure how to calculate this though.

**Comment by mbevand** [comment]
Ok. Well, the attack rate depends from region to region. There is not a single "volume" that could represent that

**Comment by schrepfler** [comment]
What I meant the main graph identifies really well how more deadly is COVID-19 compared to the common flu and broken down by age group. A part from the severity it would be interesting to see if more people got it than the common flu (total number of infections, not sure what's the best way to break it down, geography, age group, time of the year, then there's the lockdown effect)

**Comment by mbevand** [comment]
Sounds like what you want is a chart of COVID deaths vs average flu deaths per season. And a chart per country. This would both represent how much more deadly COVID is, and how the attack rate of COVID can be higher than the flu.

It's probably tedious work to find the average number of flu deaths per country...
