### ISSUE TITLE
Flu IFR estimates: is the contry table updated?

### ISSUE THREAD

**Issue by dkobak** [mbevand/covid19-age-stratified-ifr#5]
Thanks for great work. I have a question about your yesterday's update of IFR estimates for flu (based on the update of asymptomatic fraction). Have you also updated the flu estimates in the country table in README? I have a feeling that the figure is updated but the table is not. Could you confirm?

**Comment by dkobak** [comment]
Specifically, I guess you need to update the value in this line:

https://github.com/mbevand/covid19-age-stratified-ifr/blob/master/apply_ifr.py#L26

and rerun :-)

**Comment by mbevand** [comment]
You're right, I forgot to update it. Fixed in 8f3bafd2c996b07421f1dad8d626c700ae723d7e

**Comment by dkobak** [comment]
Cool, thanks!
