### ISSUE TITLE
IFR estimates from Buss et al

### ISSUE THREAD

**Issue by dkobak** [mbevand/covid19-age-stratified-ifr#7]
Supp Fig 1 in https://science.sciencemag.org/content/early/2020/12/07/science.abe9728 gives age-stratified estimates for IFR. Seems to agree with your estimates reasonably well.

I am not sure if you are looking to include more studies but if you do, then this might be of interest.

**Comment by mbevand** [comment]
Thanks. I briefly skimmed the Supplementary Material, and although I see Fig S1, I don't see a table with numerical values for the IFR. So I'm unable to incorporate them in my script. If you find them, let me know.
